# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - run: git config --global url."https://github-actions:${{secrets.GH_TOKEN}}@github.com/".insteadOf "ssh://git@github.com/"
    - run: git config --global -l
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GH_TOKEN }}
    # - uses: actions/setup-node@v4
    #   with:
    #     node-version: 16.x
    #     cache: 'npm'
    - run: git config --global -l
    - run: git --no-replace-objects ls-remote ssh://git@github.com/dangh/snasa.git
    # - run: npm i
